# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

matrix:
  include:
    - dist: xenial
      r: release
      apt_packages: libpoppler-cpp-dev
      after_success: Rscript -e 'covr::codecov(line_exclusions=list("R/fdic_doc_function.R"))'
    - dist: trusty
      r: devel
      apt_packages: libpoppler-cpp-dev
    - os: osx
      r: release

sudo: false

cache: packages
warnings_are_errors: true
r_check_args: "--as-cran"
