# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

matrix:
  include:
    - dist: xenial
      r: release
      apt_packages: libpoppler-cpp-dev
    - dist: trusty
      r: devel
      apt_packages: libpoppler-cpp-dev
    - os: osx
      r: release

sudo: false

cache: packages
